### ISSUE TITLE
Cant download the source file

### ISSUE THREAD

**Issue by demmy4bi** [john-smilga/node-express-course#8]
Good Day Sir.
Please can you guide me how to download the source code

**Comment by profalphon** [comment]
Sorry pls who is this. I have being trying to understand . But anyway go to the code section. Click on it and it would be copied.Create a new folder on your desktop, rename it and then go to vscode Redirect your directory to the folder createdThen type git clone and paste the link copied from the code

Sent from Yahoo Mail on Android 
 
  On Tue, Sep 7, 2021 at 18:33, ***@***.***> wrote:   


Closed #8.


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by demmy4bi** [comment]
thanks sir,,have gotten it,,i didnt maximize the page so i wasnt able to
see the code before

**Comment by demmy4bi** [comment]
Help me check the screenshot sir, the content not showing properly
